(import parametrized [parametrized])
(import pytest [mark])
(import oreo [first-last-n])
(setv ten (range 10))
(defn [mark.first-last-n] test-first-5 [] (assert (= (list (range 5)) (first-last-n :iterable ten :number 5 :type- list))))
(defn [mark.first-last-n] test-last-5 [] (assert (= (list (range 5 10)) (first-last-n :iterable ten :number 5 :last True :type- list))))
