(import parametrized [parametrized])
(import pytest [mark])
(import oreo [flatten])
(setv nested #(1 #(2 #(3 #(4))))
      flattened [1 2 3 4]
      outputs #(nested [1 2 #(3 #(4))] [1 2 3 #(4)] flattened)
      fives (range 5))
(defn [mark.flatten] test-flatten-one-item [] (assert (= (flatten 1) [1])))
(defn [mark.flatten] test-flatten-all [] (assert (= (flatten nested) flattened)))
(defn [mark.flatten parametrized.zip] test-flatten [[times fives] [output outputs]] (assert (= (flatten nested :times times) output)))
(defn [mark.flatten] test-flatten-all-unpacked [] (assert (= (flatten #* nested) flattened)))
(defn [mark.flatten parametrized.zip] test-flatten-unpacked [[times fives] [output outputs]] (assert (= (flatten #* nested :times times) output)))
